apiVersion: v1
kind: Service
metadata:
  name: tg-producer-service
  labels:
    app: tgproducer
spec:
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080
  selector:
   app: tgproducer 
    